# Generated by Django 5.2.12 on 2026-04-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_payment_status_order_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="stripe_payment_intent_id",
            new_name="payment_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_gateway",
            field=models.CharField(default="razorpay", max_length=50),
        ),
    ]
